### ISSUE TITLE
Error while installing with Python3

### ISSUE THREAD

**Issue by iddoberpl** [riolet/poline#16]
Iddos-MacBook-Pro:~ iddoberger$ pip3 install pol
Collecting pol
  Using cached pol-0.4.1.tar.gz
Collecting pycrypto>=2.6 (from pol)
  Using cached pycrypto-2.6.1.tar.gz
Collecting msgpack-python>=0.2 (from pol)
  Using cached msgpack-python-0.4.8.tar.gz
Collecting gmpy<2,>=1.15 (from pol)
  Using cached gmpy-1.17.zip
Collecting yappi>=0.62 (from pol)
  Using cached yappi-0.98.tar.gz
Collecting lockfile>=0.8 (from pol)
  Using cached lockfile-0.12.2-py2.py3-none-any.whl
Requirement already satisfied: PyYAML>=3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pol)
Collecting pyparsing<2.0.0,>=1.5.6 (from pol)
  Using cached pyparsing-1.5.7.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 72, in <module>
        import packaging.requirements
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/packaging/requirements.py", line 9, in <module>
        from pyparsing import stringStart, stringEnd, originalTextFor, ParseException
      File "/private/var/folders/24/c0q7ks0s7sgbkmmpxkslw4vh0000gn/T/pip-build-s4iwk21t/pyparsing/pyparsing.py", line 855
        except ParseBaseException, err:
                                 ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/24/c0q7ks0s7sgbkmmpxkslw4vh0000gn/T/pip-build-s4iwk21t/pyparsing/

**Comment by rrezel** [comment]
Hey there,

The name of the package is **poline**.

We had to name it as such because pol was already taken.

Sorry about that.

Thanks!

**Comment by iddoberpl** [comment]
Thanks!
